In [2]:
import numpy as np
import pandas as pd
from scipy.stats import fisher_exact

In [3]:
df_or = pd.read_csv('df_or.csv')

/home/ziwen/.local/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3553: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [4]:
len(df_or)

10527244

In [5]:
del df_or[df_or.columns[0]]

In [6]:
df_or.head()

,FRACE15,MRACE15,DMAR,MEDUC,FEDUC,MBSTATE_REC,PAY_REC,RF_PDIAB,RF_GDIAB,RF_PHYPE,...,RF_INFT,NO_INFEC,MAGER,FAGECOMB,BMI,TPO_REC,OEGest_Comb,ME_PRES,BFACIL,RDMETH_REC
0,1,1,1,6,3,1,2,N,N,N,...,N,1,30,31,30.7,4,40,1,1,1
1,3,3,2,9,4,1,1,N,N,N,...,N,1,35,35,33.3,3,39,1,1,4
2,1,1,1,6,4,1,4,N,N,Y,...,N,1,28,31,30.0,2,36,1,1,1
3,3,3,2,2,2,1,1,N,N,N,...,N,1,23,26,23.7,3,39,1,1,1
4,2,1,1,4,3,1,1,N,N,N,...,N,1,37,35,35.5,6,37,1,1,3

In [7]:
# apply additional criteria
df_or = df_or.loc[(df_or['OEGest_Comb'] >= 37) & (df_or['OEGest_Comb'] <= 43) & (df_or['ME_PRES'] ==  1) & (df_or['BFACIL'] == 1)]

# TPO_REC=1
df_or = df_or[df_or['TPO_REC'] == 1] 

# only include RDMETH_REC = 1, 3, 9
df_or = df_or[df_or['RDMETH_REC'].isin([1, 3, 9])]

In [8]:
len(df_or)

2943442

In [9]:
# recode the variables
def DMAR_recode(x):
    if x == 1:
        return 1
    elif x == 2:
        return 2
    else: 
        return np.NAN # need to check!
    
def MEDUC_recode(x):
    if x == 1 or x == 2:
        return 1
    elif x >= 3 and x <= 8:
        return 2
    else: 
        return np.NAN

def FEDUC_recode(x):
    if x == 1 or x == 2:
        return 1
    elif x >= 3 and x <= 8:
        return 2
    else: 
        return np.NAN
    
def MBSTATE_REC_recode(x):
    if x == 1:
        return 1
    elif x == 2:
        return 2
    else: 
        return np.NAN
    
def PAY_REC_recode(x):
    if x == 1:
        return 1
    elif x == 2:
        return 2
    elif x == 3:
        return 3
    elif x == 4:
        return 4
    else: 
        return np.NAN
    
def RF_recode(x):
    if x == 'Y':
        return 1
    elif x == 'N':
        return 2
    else: 
        return np.NAN
    
def SEX_recode(x):
    if x == 'F':
        return 1
    else: 
        return 2
    
def PRECARE_recode(x):
    if x == 0:
        return 2
    elif x >=1 and x <= 10:
        return 1
    else: 
        return np.NAN
    
def NO_INFEC_recode(x):
    if x == 0:
        return 2
    elif x == 1:
        return 1
    else: 
        return np.NAN

def RDMETH_REC_recode(x):
    if x == 1:
        return 0
    elif x == 3:
        return 1
    else: 
        return np.NAN
    
# def TPO_REC_recode(x):
#     if x == 1:
#         return 1
#     elif x == 2:
#         return 2
#     elif x == 3:
#         return 3
#     elif x == 4:
#         return 4
#     elif x == 5:
#         return 5
#     elif x == 6:
#         return 6
#     elif x == 7:
#         return 7
#     elif x == 8:
#         return 8
#     else: 
#         return 'Missing'

    
df_or['DMAR'] = df_or['DMAR'].apply(DMAR_recode)
df_or['MEDUC'] = df_or['MEDUC'].apply(MEDUC_recode)
df_or['FEDUC'] = df_or['FEDUC'].apply(FEDUC_recode)
df_or['MBSTATE_REC'] = df_or['MBSTATE_REC'].apply(MBSTATE_REC_recode)
df_or['PAY_REC'] = df_or['PAY_REC'].apply(PAY_REC_recode)
df_or['RF_PDIAB'] = df_or['RF_PDIAB'].apply(RF_recode)
df_or['RF_GDIAB'] = df_or['RF_GDIAB'].apply(RF_recode)
df_or['RF_PHYPE'] = df_or['RF_PHYPE'].apply(RF_recode)
df_or['RF_GHYPE'] = df_or['RF_GHYPE'].apply(RF_recode)
df_or['RF_EHYPE'] = df_or['RF_EHYPE'].apply(RF_recode)
df_or['RF_PPB'] = df_or['RF_PPB'].apply(RF_recode)
df_or['SEX'] = df_or['SEX'].apply(SEX_recode)
df_or['CIG_REC'] = df_or['CIG_REC'].apply(RF_recode)
df_or['PRECARE'] = df_or['PRECARE'].apply(PRECARE_recode)
df_or['RF_INFT'] = df_or['RF_INFT'].apply(RF_recode)
df_or['NO_INFEC'] = df_or['NO_INFEC'].apply(NO_INFEC_recode)
df_or['RDMETH_REC'] = df_or['RDMETH_REC'].apply(RDMETH_REC_recode)
# df['TPO_REC'] = df['TPO_REC'].apply(TPO_REC_recode)

In [11]:
print(df_or['DMAR'].unique())
print(df_or['MEDUC'].unique())
print(df_or['FEDUC'].unique())
print(df_or['MBSTATE_REC'].unique())
print(df_or['PAY_REC'].unique())
print(df_or['RF_PDIAB'].unique())
print(df_or['RF_GDIAB'].unique())
print(df_or['RF_PHYPE'].unique())
print(df_or['RF_GHYPE'].unique())
print(df_or['RF_EHYPE'].unique())
print(df_or['RF_PPB'].unique())
print(df_or['SEX'].unique())
print(df_or['CIG_REC'].unique())
print(df_or['PRECARE'].unique())
print(df_or['RF_INFT'].unique())
print(df_or['NO_INFEC'].unique())
print(df_or['TPO_REC'].unique())
print(df_or['RDMETH_REC'].unique())

[ 1.  2. nan]
[ 2.  1. nan]
[ 2.  1. nan]
[ 1.  2. nan]
[ 2.  4.  1.  3. nan]
[ 2.  1. nan]
[ 2.  1. nan]
[ 2.  1. nan]
[ 2.  1. nan]
[ 2.  1. nan]
[ 2. nan  1.]
[1 2]
[ 2.  1. nan]
[ 1.  2. nan]
[ 2.  1. nan]
[ 1.  2. nan]
[1]
[ 1.  0. nan]

In [12]:
len(df_or)

2943442

In [21]:
df_or.columns.values

array(['FRACE15', 'MRACE15', 'DMAR', 'MEDUC', 'FEDUC', 'MBSTATE_REC',
       'PAY_REC', 'RF_PDIAB', 'RF_GDIAB', 'RF_PHYPE', 'RF_GHYPE',
       'RF_EHYPE', 'RF_PPB', 'SEX', 'CIG_REC', 'PRECARE', 'RF_INFT',
       'NO_INFEC', 'MAGER', 'FAGECOMB', 'BMI', 'TPO_REC', 'OEGest_Comb',
       'ME_PRES', 'BFACIL', 'RDMETH_REC', 'Ethnicity Category',
       'Ethnicity Description'], dtype=object)

In [22]:
df_or.head()

,FRACE15,MRACE15,DMAR,MEDUC,FEDUC,MBSTATE_REC,PAY_REC,RF_PDIAB,RF_GDIAB,RF_PHYPE,...,MAGER,FAGECOMB,BMI,TPO_REC,OEGest_Comb,ME_PRES,BFACIL,RDMETH_REC,Ethnicity Category,Ethnicity Description
7,1,1,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,...,31,29,28.2,1,40,1,1,1.0,1,Both White (only)
9,1,1,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,...,26,28,19.8,1,38,1,1,0.0,1,Both White (only)
11,1,1,1.0,2.0,2.0,1.0,4.0,2.0,2.0,2.0,...,27,26,24.3,1,40,1,1,1.0,1,Both White (only)
17,10,10,2.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,...,21,22,25.2,1,39,1,1,0.0,10,Both Other Asian (only)
21,10,10,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,...,25,27,32.2,1,39,1,1,0.0,10,Both Other Asian (only)

In [17]:
df_or['Ethnicity Category'] = 'initial'
df_or.loc[(df_or['MRACE15'] == 1) & (df_or['FRACE15'] == 1), 'Ethnicity Category'] = 1
df_or.loc[(df_or['MRACE15'] == 2) & (df_or['FRACE15'] == 2), 'Ethnicity Category'] = 2
df_or.loc[(df_or['MRACE15'] == 3) & (df_or['FRACE15'] == 3), 'Ethnicity Category'] = 3
df_or.loc[(df_or['MRACE15'] == 4) & (df_or['FRACE15'] == 4), 'Ethnicity Category'] = 4
df_or.loc[(df_or['MRACE15'] == 5) & (df_or['FRACE15'] == 5), 'Ethnicity Category'] = 5
df_or.loc[(df_or['MRACE15'] == 6) & (df_or['FRACE15'] == 6), 'Ethnicity Category'] = 6
df_or.loc[(df_or['MRACE15'] == 7) & (df_or['FRACE15'] == 7), 'Ethnicity Category'] = 7
df_or.loc[(df_or['MRACE15'] == 8) & (df_or['FRACE15'] == 8), 'Ethnicity Category'] = 8
df_or.loc[(df_or['MRACE15'] == 9) & (df_or['FRACE15'] == 9), 'Ethnicity Category'] = 9
df_or.loc[(df_or['MRACE15'] == 10) & (df_or['FRACE15'] == 10), 'Ethnicity Category'] = 10
df_or.loc[(df_or['MRACE15'] == 11) & (df_or['FRACE15'] == 11), 'Ethnicity Category'] = 11
df_or.loc[(df_or['MRACE15'] == 12) & (df_or['FRACE15'] == 12), 'Ethnicity Category'] = 12
df_or.loc[(df_or['MRACE15'] == 13) & (df_or['FRACE15'] == 13), 'Ethnicity Category'] = 13
df_or.loc[(df_or['MRACE15'] == 14) & (df_or['FRACE15'] == 14), 'Ethnicity Category'] = 14
df_or.loc[(df_or['MRACE15'] == 15) & (df_or['FRACE15'] == 15), 'Ethnicity Category'] = 15
df_or.loc[(df_or['MRACE15'] == 1) & (df_or['FRACE15'] != 1) & (df_or['FRACE15'] >= 1) & (df_or['FRACE15'] <= 15), 'Ethnicity Category'] = 16
df_or.loc[(df_or['MRACE15'] == 2) & (df_or['FRACE15'] != 2) & (df_or['FRACE15'] >= 1) & (df_or['FRACE15'] <= 15), 'Ethnicity Category'] = 17
df_or.loc[(df_or['MRACE15'] == 3) & (df_or['FRACE15'] != 3) & (df_or['FRACE15'] >= 1) & (df_or['FRACE15'] <= 15), 'Ethnicity Category'] = 18
df_or.loc[(df_or['MRACE15'] == 4) & (df_or['FRACE15'] != 4) & (df_or['FRACE15'] >= 1) & (df_or['FRACE15'] <= 15), 'Ethnicity Category'] = 19
df_or.loc[(df_or['MRACE15'] == 5) & (df_or['FRACE15'] != 5) & (df_or['FRACE15'] >= 1) & (df_or['FRACE15'] <= 15), 'Ethnicity Category'] = 20
df_or.loc[(df_or['MRACE15'] == 6) & (df_or['FRACE15'] != 6) & (df_or['FRACE15'] >= 1) & (df_or['FRACE15'] <= 15), 'Ethnicity Category'] = 21
df_or.loc[(df_or['MRACE15'] == 7) & (df_or['FRACE15'] != 7) & (df_or['FRACE15'] >= 1) & (df_or['FRACE15'] <= 15), 'Ethnicity Category'] = 22
df_or.loc[(df_or['MRACE15'] == 8) & (df_or['FRACE15'] != 8) & (df_or['FRACE15'] >= 1) & (df_or['FRACE15'] <= 15), 'Ethnicity Category'] = 23
df_or.loc[(df_or['MRACE15'] == 9) & (df_or['FRACE15'] != 9) & (df_or['FRACE15'] >= 1) & (df_or['FRACE15'] <= 15), 'Ethnicity Category'] = 24
df_or.loc[(df_or['MRACE15'] == 10) & (df_or['FRACE15'] != 10) & (df_or['FRACE15'] >= 1) & (df_or['FRACE15'] <= 15), 'Ethnicity Category'] = 25
df_or.loc[(df_or['MRACE15'] == 11) & (df_or['FRACE15'] != 11) & (df_or['FRACE15'] >= 1) & (df_or['FRACE15'] <= 15), 'Ethnicity Category'] = 26
df_or.loc[(df_or['MRACE15'] == 12) & (df_or['FRACE15'] != 12) & (df_or['FRACE15'] >= 1) & (df_or['FRACE15'] <= 15), 'Ethnicity Category'] = 27
df_or.loc[(df_or['MRACE15'] == 13) & (df_or['FRACE15'] != 13) & (df_or['FRACE15'] >= 1) & (df_or['FRACE15'] <= 15), 'Ethnicity Category'] = 28
df_or.loc[(df_or['MRACE15'] == 14) & (df_or['FRACE15'] != 14) & (df_or['FRACE15'] >= 1) & (df_or['FRACE15'] <= 15), 'Ethnicity Category'] = 29
df_or.loc[(df_or['MRACE15'] == 15) & (df_or['FRACE15'] != 15) & (df_or['FRACE15'] >= 1) & (df_or['FRACE15'] <= 15), 'Ethnicity Category'] = 30

In [20]:
df_or['Ethnicity Description'] = 'initial'
df_or.loc[(df_or['MRACE15'] == 1) & (df_or['FRACE15'] == 1), 'Ethnicity Description'] = 'Both White (only)'
df_or.loc[(df_or['MRACE15'] == 2) & (df_or['FRACE15'] == 2), 'Ethnicity Description'] = 'Both Black (only)'
df_or.loc[(df_or['MRACE15'] == 3) & (df_or['FRACE15'] == 3), 'Ethnicity Description'] = 'Both AIAN (only)'
df_or.loc[(df_or['MRACE15'] == 4) & (df_or['FRACE15'] == 4), 'Ethnicity Description'] = 'Both Asian Indian (only)'
df_or.loc[(df_or['MRACE15'] == 5) & (df_or['FRACE15'] == 5), 'Ethnicity Description'] = 'Both Chinese (only)'
df_or.loc[(df_or['MRACE15'] == 6) & (df_or['FRACE15'] == 6), 'Ethnicity Description'] = 'Both Filipino (only)'
df_or.loc[(df_or['MRACE15'] == 7) & (df_or['FRACE15'] == 7), 'Ethnicity Description'] = 'Both Japanese (only)'
df_or.loc[(df_or['MRACE15'] == 8) & (df_or['FRACE15'] == 8), 'Ethnicity Description'] = 'Both Korean (only)'
df_or.loc[(df_or['MRACE15'] == 9) & (df_or['FRACE15'] == 9), 'Ethnicity Description'] = 'Both Vietnamese (only)'
df_or.loc[(df_or['MRACE15'] == 10) & (df_or['FRACE15'] == 10), 'Ethnicity Description'] = 'Both Other Asian (only)'
df_or.loc[(df_or['MRACE15'] == 11) & (df_or['FRACE15'] == 11), 'Ethnicity Description'] = 'Both Hawaiian (only)'
df_or.loc[(df_or['MRACE15'] == 12) & (df_or['FRACE15'] == 12), 'Ethnicity Description'] = 'Both Guamanian (only)'
df_or.loc[(df_or['MRACE15'] == 13) & (df_or['FRACE15'] == 13), 'Ethnicity Description'] = 'Both Samoan (only)'
df_or.loc[(df_or['MRACE15'] == 14) & (df_or['FRACE15'] == 14), 'Ethnicity Description'] = 'Both Other Pacific Islander (only)'
df_or.loc[(df_or['MRACE15'] == 15) & (df_or['FRACE15'] == 15), 'Ethnicity Description'] = 'Both More than one race	'
df_or.loc[(df_or['MRACE15'] == 1) & (df_or['FRACE15'] != 1) & (df_or['FRACE15'] >= 1) & (df_or['FRACE15'] <= 15), 'Ethnicity Description'] = 'Mother White (only) and Father non-white'
df_or.loc[(df_or['MRACE15'] == 2) & (df_or['FRACE15'] != 2) & (df_or['FRACE15'] >= 1) & (df_or['FRACE15'] <= 15), 'Ethnicity Description'] = 'Mother Black (only) and Father non-black'
df_or.loc[(df_or['MRACE15'] == 3) & (df_or['FRACE15'] != 3) & (df_or['FRACE15'] >= 1) & (df_or['FRACE15'] <= 15), 'Ethnicity Description'] = 'Mother AIAN (only) and Father non-AIAN'
df_or.loc[(df_or['MRACE15'] == 4) & (df_or['FRACE15'] != 4) & (df_or['FRACE15'] >= 1) & (df_or['FRACE15'] <= 15), 'Ethnicity Description'] = 'Mother Asian Indian (only) and Father non-Asian'
df_or.loc[(df_or['MRACE15'] == 5) & (df_or['FRACE15'] != 5) & (df_or['FRACE15'] >= 1) & (df_or['FRACE15'] <= 15), 'Ethnicity Description'] = 'Mother Chinese (only) and Father non-Chinese'
df_or.loc[(df_or['MRACE15'] == 6) & (df_or['FRACE15'] != 6) & (df_or['FRACE15'] >= 1) & (df_or['FRACE15'] <= 15), 'Ethnicity Description'] = 'Mother Filipino (only) and Father non-Filipino'
df_or.loc[(df_or['MRACE15'] == 7) & (df_or['FRACE15'] != 7) & (df_or['FRACE15'] >= 1) & (df_or['FRACE15'] <= 15), 'Ethnicity Description'] = 'Mother Japanese (only) and Father non-Japanese'
df_or.loc[(df_or['MRACE15'] == 8) & (df_or['FRACE15'] != 8) & (df_or['FRACE15'] >= 1) & (df_or['FRACE15'] <= 15), 'Ethnicity Description'] = 'Mother Korean (only) and Father non-Korean'
df_or.loc[(df_or['MRACE15'] == 9) & (df_or['FRACE15'] != 9) & (df_or['FRACE15'] >= 1) & (df_or['FRACE15'] <= 15), 'Ethnicity Description'] = 'Mother Vietnamese (only) and Father non-Vietnamese'
df_or.loc[(df_or['MRACE15'] == 10) & (df_or['FRACE15'] != 10) & (df_or['FRACE15'] >= 1) & (df_or['FRACE15'] <= 15), 'Ethnicity Description'] = 'Mother Other Asian (only) and Father non-Other Asian'
df_or.loc[(df_or['MRACE15'] == 11) & (df_or['FRACE15'] != 11) & (df_or['FRACE15'] >= 1) & (df_or['FRACE15'] <= 15), 'Ethnicity Description'] = 'Mother Hawaiian (only) and Father non-Hawaiian'
df_or.loc[(df_or['MRACE15'] == 12) & (df_or['FRACE15'] != 12) & (df_or['FRACE15'] >= 1) & (df_or['FRACE15'] <= 15), 'Ethnicity Description'] = 'Mother Guamanian (only) and Father non-Guamanian'
df_or.loc[(df_or['MRACE15'] == 13) & (df_or['FRACE15'] != 13) & (df_or['FRACE15'] >= 1) & (df_or['FRACE15'] <= 15), 'Ethnicity Description'] = 'Mother Samoan (only) and Father non-Samoan'
df_or.loc[(df_or['MRACE15'] == 14) & (df_or['FRACE15'] != 14) & (df_or['FRACE15'] >= 1) & (df_or['FRACE15'] <= 15), 'Ethnicity Description'] = 'Mother Other Pacific Islander (only) and Father non-Other Pacific Islander'
df_or.loc[(df_or['MRACE15'] == 15) & (df_or['FRACE15'] != 15) & (df_or['FRACE15'] >= 1) & (df_or['FRACE15'] <= 15), 'Ethnicity Description'] = 'Mother More than one race and Father non-More than one race'

In [24]:
df_or.to_csv('df_odds_ratio.csv')

In [25]:
len(df_or)

2943442

In [13]:
df_or['DMAR'].unique() # interesting...

array([1, 2, '1', '2', ' '], dtype=object)

In [14]:
a = df_or.loc[(df_or['MRACE15'] == 1) & (df_or['FRACE15'] == 1) & (df_or['RDMETH_REC'] == 1)] # both white
b = df_or.loc[(df_or['MRACE15'] == 1) & (df_or['FRACE15'] == 1) & df_or['RDMETH_REC'] == 1)]
c = df_or.loc[(df_or['MRACE15'] == 1) & (df_or['FRACE15'] == 1) & (df_or['RDMETH_REC'] == 0)]
d = df_or.loc[(df_or['MRACE15'] == 1) & (df_or['FRACE15'] == 1) & (df_or['RDMETH_REC'] == 0)]

In [15]:
a = len(a)  # count in Treatment 1 with the outcome
b = len(b)  # count in Treatment 2 with the outcome
c = len(c)  # count in Treatment 1 without the outcome
d = len(d)  # count in Treatment 2 without the outcome

# Treatment - ETHNICITY GROUPS (BOTH WHITE AS reference)
# OUTCOME - RDMETH_REC

# Adjust ORs: control another confounding

# send the dataset adding one column - enthnicity + word description; check the recode; also send the 

# Create a 2x2 contingency table
contingency_table = [[a, b], [c, d]]

# Calculate odds ratio and p-value
odds_ratio, p_value = fisher_exact(contingency_table)

print(f'Odds Ratio: {odds_ratio}')
print(f'P-value: {p_value}')

Odds Ratio: 1.0702193756786824
P-value: 5.700182924187055e-59